<?php
/*
 * @author: Scottish Borders Design
 * @script: SBD SHOUTcast Manager
 * @function: API - WHMCS Server Module
 * @website: http://scottishbordersdesign.co.uk/
 * @useage: See Developer Docs
*/
if (!isset($_POST['class']) || empty($_POST)) {
    die("NO AUTH!");
}
require ('../include/functions.inc.php');
$config = settings();
$username = 'WHMCS';
ob_start();
if (!$_POST['shoutcusername']) {
    $scUsername = uniqid();
} else {
    $scUsername = $_POST['shoutcusername'];
}
$isauser = useraccess($scUsername);
$debug = '';
if (empty($isauser)) {
    adduser($scUsername, md5($_POST['adminpassword']), $_POST['first_name'], $_POST['last_name'], $_POST['email'], '1');
    $userid = getuid($scUsername);
} else {
    $userid = getuid($scUsername);
}
$output = ob_get_clean();
if ($scUsername) {
    // New servers are by default "not enabled"
    $enabled = 0;
    // Fetch values from form
    $srvname = $_POST['srvname'];
    $srvname = preg_replace('/\s/', '_', $srvname);
    $portbase = nextport();
    $adminpassword = $_POST['adminpassword'];
    $djpassword = $_POST['djpassword'];
    $maxuser = $_POST['maxuser'];
    $bitrate = $_POST['bitrate'];
    /* Pre-Defined Data */
    $realtime = 1;
    $screenlog = 1;
    $showlastsongs = 10;
    $w3cenable = 'yes';
    $srcip = 'ANY';
    $dstip = 'ANY';
    $yport = 80;
    $namelookup = 0;
    // If form's relayport is not set, assign '0' as values to relay port & host
    if (isset($_POST['isrelay'])) {
        $relayport = $_POST['relayport'];
        $relayhost = $_POST['relayhost'];
    } else {
        $relayport = '0';
        $relayhost = '0';
    }
    /* to do create user and return id */
    $uid = $userid;
    $autodump = 0;
    $autodumptime = 30;
    $publicsrv = $_POST['publicsrv']; // if ticket = default
    $allowrelay = 'Yes';
    $allowpublicrelay = 'Yes';
    $metainterval = '32768';
    if (isset($_POST['genre'])) {
        $genre = $_POST['genre'];
    } else {
        $genre = '';
    }
    if (isset($_POST['website'])) {
        $website = $_POST['website'];
    } else {
        $website = '';
    }
    $autodjspace = $_POST['autodj_space'];
    $autodjspace = ($autodjspace * 1024);
    // Define common insert fields and values
    $insert = array(
        'owner' => $uid, 
        'AdminPassword' => $adminpassword, 
        'servername' => $srvname, 
        'created' => $username, 
        'MaxUser' => $maxuser, 
        'Password' => $djpassword, 
        'PortBase' => $portbase, 
        'RealTime' => $realtime, 
        'ScreenLog' => $screenlog, 
        'ShowLastSongs' => $showlastsongs, 
        'W3CEnable' => $w3cenable, 
        'SrcIP' => $srcip, 
        'DestIP' => $dstip, 
        'Yport' => $yport, 
        'NameLookups' => $namelookup, 
        'RelayPort' => $relayport, 
        'RelayServer' => $relayhost, 
        'AutoDumpUsers' => $autodump, 
        'AutoDumpSourceTime' => $autodumptime, 
        'PublicServer' => $publicsrv, 
        'AllowRelay' => $allowrelay, 
        'AllowPublicRelay' => $allowpublicrelay, 
        'MetaInterval' => $metainterval, 
        'bitrate' => $bitrate, 
        'autodj_max_space' => $autodjspace, 
        'autodj_used_space' => '0',
        'autodj_crossfadeMode' => '1',
        'autodj_crossfadeseconds' => '5000'
    );
    // If AutoDJ is set, generate SC_SERV config file and playlist
    newPlaylist($portbase, $uid);
    buildPlaylist($portbase);
    $header = ";
" . "; $srvname Configuration file
" . "; Auto-generated by SBD
" . ";
" . "PlaylistFile={$config['sbd_path']}/playlists/autodj_$portbase.lst
" . "ServerIP={$config['host_addr']}
" . "ServerPort=$portbase
" . "Password=$djpassword
" . "StreamTitle=$srvname
" . "StreamURL=$website
" . "Genre=$genre
" . "Shuffle=0
" . "; Bitrate/SampleRate/Channels recommended values:
" . "; 8kbps 8000/11025/1
" . "; 16kbps 16000/11025/1
" . "; 24kbps 24000/22050/1
" . "; 32kbps 32000/22050/1
" . "; 64kbps mono 64000/44100/1
" . "; 64kbps stereo 64000/22050/2
" . "; 96kbps stereo 96000/44100/2
" . "; 128kbps stere0 128000/44100/2
" . "InputSamplerate=44100
" . "InputChannels=2
" . "Bitrate={$bitrate}000
" . "SampleRate=44100
" . "Channels=2
" . "Quality=5
" . "CrossfadeMode=1
" . "CrossfadeLength=5000
" . "UseID3=0
" . "Public=0
" . "AIM=
" . "ICQ=
" . "IRC=
";
    // Save the configuration file
    $fd = fopen($config['sbd_path'] . "/servers/autodj_" . $portbase . "" . $srvname . ".conf", "w");
    fputs($fd, $header . "
");
    fclose($fd);
    // Do the actual insert
    $db = dbConnect();
    $id = $db->insert('servers', $insert);
    // Now create the FTP for the AutoDJ (even if they dont have it enabled, it saves trouble adding it now, than later!)
	mkdir($config['media_path'].$portbase.'/', 0777);
    // Create event in event log
    $event = " created a new server with id " . $id . " on port " . $portbase;
    addevent($username, $event);
    // Run MRTG update
    generatemrtg();
    // Set up sc_serv config file for this server
    $header = ";
" . "; $srvname Configuration file
" . "; Auto-generated by SBD
" . ";
" . "AdminPassword=$adminpassword
" . "MaxUser=$maxuser
" . "Password=$djpassword
" . "PortBase=$portbase
" . "RealTime=$realtime
" . "ScreenLog=$screenlog
" . "ShowLastSongs=$showlastsongs
" . "W3CEnable=$w3cenable
" . "SrcIP=$srcip
" . "DestIP=$dstip
" . "Yport=$yport
" . "NameLookups=$namelookup
";
    if ($relayport > 0) {
        $header.= "RelayPort=$relayport
" . "RelayServer=$relayhost
";
    }
    $header.= "AutoDumpUsers=$autodump
" . "AutoDumpSourceTime=$autodumptime
" . "PublicServer=$publicsrv
" . "AllowRelay=$allowrelay
" . "AllowPublicRelay=$allowpublicrelay
" . "BanFile=" . $config['sbd_path'] . "/logs/$portbase$srvname.ban
" . "LogFile=" . $config['sbd_path'] . "/logs/$portbase$srvname.log
" . "W3CLog=" . $config['sbd_path'] . "/logs/$portbase$srvname.w3c.log
" . "MetaInterval=$metainterval
";
    // Save the configuration file
    $fd = fopen($config['sbd_path'] . "/servers/" . $portbase . "" . $srvname . ".conf", "w+");
    fputs($fd, $header . "
");
    fclose($fd);
    // If enabled start on creation, start the server
    if ($config['auto_start'] == "on") {
        startstream($id);
    }
    die('success');
} else {
    die('No Post Info!');
}
?>